# Generated by Django 5.0.1 on 2024-06-08 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
